apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vulnerable-app-demo
  template:
    metadata:
      labels:
        app: vulnerable-app-demo
    spec:
      containers:
      - name: vulnerable-app-demo
        image: trusted.registry.local/vulnerable-app-demo:latest
        ports:
        - containerPort: 443
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
