apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: silly-demo-ingress
  namespace: demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: silly-demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: silly-demo
            port:
              number: 8080
