name: Kubernetes PAC and Zero Trust Demo

on: push
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Validate conftest
      uses: instrumenta/conftest-action@master
      with:
        files: deployment.yaml
